# <center>Assignment 4

Name:

# Part 1

**In part 1 you need to work with data from the about 120 years of Olympic history by pandas. Write code and perform computations in the cells below. There are five questions.**

Download the file `athlete_events.csv` from [here](https://www.kaggle.com/datasets/heesoo37/120-years-of-olympic-history-athletes-and-results). The dataset has the following features:

- __ID__ - Unique number for each athlete
- __Name__ - Athlete's name
- __Sex__ - M or F
- __Age__ - Integer
- __Height__ - In centimeters
- __Weight__ - In kilograms
- __Team__ - Team name
- __NOC__ - National Olympic Committee 3-letter code
- __Games__ - Year and season
- __Year__ - Integer
- __Season__ - Summer or Winter
- __City__ - Host city
- __Sport__ - Sport
- __Event__ - Event
- __Medal__ - Gold, Silver, Bronze, or NA

In [ ]:
import pandas as pd

In [ ]:
PATH = 'athlete_events.csv'

In [ ]:
data = pd.read_csv(PATH)
data.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

__1. How old were the oldest male and female participants of the 2012 Olympics?__

__2. What are the mean and standard deviation of height for male basketball players who participated in the 1992 Olympics? Round the answer to the first decimal.__

__3. How many times did Christine Jacoba Aaftink participate in the Olympics held in different years?__

__4. Is it true that China won fewer medals than Russia at the 2012 Olympics? Do not consider NaN values in Medal column.__

__5. What is the absolute difference between the number of unique sports at the 1986 Olympics and 2016 Olympics?__

# Part 2

**In part 2 you need to work with numpy library. Write code and perform computations in the cells below. There are five questions.**

In [ ]:
import numpy as np

__6. Create a 5x5 matrix with row values ranging from 0 to 4__

__7. Create a random vector of size 10 and sort it__

__8. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area__

In [ ]:
import numpy as np
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.88888889, 0.33333333) (1.        , 0.33333333)]
 [(0.        , 0.44444444) (0.11111111, 0.44444444)
  (0.22222222, 0.44444444) (0.33333333, 0.44444444)
  (0.44444444, 0.44444444) (0.55555556, 0.44444444)
  (0.66666667, 0.44444444) (0.77777778, 0.44444444)
  (0.88888889, 0.44444444) (1.        , 0.44444444)]
 [(0.        , 0.55555556) (0.11111111, 0.55555556)
  (0.22222222, 0.55555556) (0.33333333, 0.55555556)
  (0.44444444, 0.55555556) (0.55555556, 0.55555556)
  (0.66666667, 0.55555556) (0.77777778, 0.55555556)
  (0.88888889, 0.55555556) (1.        , 0.55555556)]
 [(0.        , 0.66666667) (0.11111111, 0.66666667)
  (0.22222222, 0.66666667) (0.33333333, 0.66666667)
  (0.44444444, 0.66666667) (0.55555556, 0.66666667)
  (0.66666667, 0.66666667) (0.77777778, 0.66666667)
  (0.88888889, 0.66666667) (1.        , 0.66666667)]
 [(0.        , 0.77777778) (0.11111111, 0.77777778)
  (0.22222222, 0.77777778) (0.33333333, 0.77777778)
  (0.44444444, 0.77777778) (0.55555556, 0.77777778)
  (0.66666667, 0.77777778) (0.77777778, 0.77777778)
  (0.88888889, 0.77777778) (1.        , 0.77777778)]
 [(0.        , 0.88888889) (0.11111111, 0.88888889)
  (0.22222222, 0.88888889) (0.33333333, 0.88888889)
  (0.44444444, 0.88888889) (0.55555556, 0.88888889)
  (0.66666667, 0.88888889) (0.77777778, 0.88888889)
  (0.88888889, 0.88888889) (1.        , 0.88888889)]
 [(0.        , 1.        ) (0.11111111, 1.        )
  (0.22222222, 1.        ) (0.33333333, 1.        )
  (0.44444444, 1.        ) (0.55555556, 1.        )
  (0.66666667, 1.        ) (0.77777778, 1.        )
  (0.88888889, 1.        ) (1.        , 1.        )]]

__9. Consider two random array A and B, check if they are equal__

__10. Create a random matrix and swap two rows of an array?__